### ISSUE TITLE
Release is a fat jar with bundled dependencies

### ISSUE THREAD

**Issue by uwemaurer** [ferortega/cf4j#11]
Hi,

I noticed that the release jar file is about 500Mb in size! And it bundles all the dependencies inside the jar. This gave me trouble because of a version conflict and duplicated classes on the classpath of different versions.

It would be great if you could provide a normal release aswell without the bundled dependencies.

For now I made a fork (https://github.com/atexp/cf4j/commits/master) which allows to build a release with jitpack and depend on that.

Thank you for this library, it helped me a lot to get started quickly with a recommender!

**Comment by ferortega** [comment]
Hi,

Thank you for your contribution. It would be great if you could make a pull request with these changes to include them into the repository.

Best regards

**Comment by ferortega** [comment]
In the new versions, we are going to upload a release without the bundled dependencies.
