### ISSUE TITLE
Mismatch in number of items

### ISSUE THREAD

**Issue by vermavijay** [ferortega/cf4j#4]
In Movielens 1M dataset, the number of movies is ~ 3900 (i.e. 3883) as specified in the dataset.

But using the CF4J library's kernel, if we find the number of items in the dataset by using the method "getNumberOfItems()" it only prints 3706 items.

why is it so? Plz, explain @ferortega

**Comment by ferortega** [comment]
@vermavijay i have analyzed the MovieLens 1M dataset file and it contains 3706 items.

Here is the code to test it:

`BufferedReader dataset = new BufferedReader (new FileReader (new File ("MovieLens1M.txt")));
		
		Set <Integer> items = new HashSet <Integer> ();
		
		String line = "";
		while ((line = dataset.readLine()) != null) {
			String [] s = line.split("::");
			int item = Integer.parseInt(s[1]);
			items.add(item);
		}
		
		System.out.println(items.size());

		dataset.close();`
