### ISSUE TITLE
Adjusted cosine similarity

### ISSUE THREAD

**Issue by vermavijay** [ferortega/cf4j#5]
Dear Sir @ferortega, 
We know that Adjusted cosine similarity measure (ACOS) had been introduced to measure the similarity between items [Ref. Article Below], why cf4j framework includes this measure, ACOS, to calculate the similarity between users via class: cf4j.knn.userToUser.similarities.MetricAjustedCosine?

**Article:**
Sarwar, Badrul, George Karypis, Joseph Konstan, and John Reidl. 2001. “Item-Based Collaborative Filtering Recommendation Algorithms.” Proceedings of the Tenth International Conference on World Wide Web  - WWW ’01, 285–95

**Comment by ferortega** [comment]
Dear @vermavijay,

To compute the similarity between items or users is mathematically the same. We decided to include ACOS for users in order to used as baseline in future works. Its usage is optional.

**Comment by vermavijay** [comment]
Thanks for such a quick response.
