### ISSUE TITLE
% value in the console

### ISSUE THREAD

**Issue by vermavijay** [ferortega/cf4j#6]
Dear @ferortega Sir,

During execution of a UBCF on 20M dataset, the 
[sample_console.docx](https://github.com/ferortega/cf4j/files/2805271/sample_console.docx)
console shows some % values. Can you please explain what are these values??

Example: attached file

**Comment by ferortega** [comment]
Is the percentage of user/items processed.

**Comment by vermavijay** [comment]
Yes, these are processed on a high-performance machine.
Please have a look at the attached document in the issue.

**Comment by ferortega** [comment]
I do not undestand the problem...
