### ISSUE TITLE
DatasetSplitters

### ISSUE THREAD

**Issue by marciabarros** [ferortega/cf4j#8]
Hi, 

would it be possible for you to provide a small example of how to use the explicit DatasetSplitters?

Best Regards,
Márcia Barros

**Comment by kasios** [comment]
Hi marciabarros, 

Basically you just have to build a comparison function like the one shown in the DataSetSpillter class.
The main idea is to make a lambda function that accepts two parameters.
Here is an example taken from that class:

public static BiFunction <Integer, Map <Integer, Double>, Boolean> maxNumberOfRatings (int maxNumberOfRatings) {
		return (code, ratings) -> { return ratings.size() <= maxNumberOfRatings; }; 
}

Once the function is done, you only have to pass it to the kernel constructor to filter with your desired criteria. The necessary constructor is the following:

void open (String filename, BiFunction <Integer, Map <Integer, Double>, Boolean> testUserFilter, 
BiFunction <Integer, Map <Integer, Double>, Boolean> testItemFilter, String separator);

As you can see, it accepts two filtering functions, one for users and a different one for Items (or the same one)

Given the first function, an example of use would be as follows (assuming the method is defined in the same class where you are loading the dataset):

this.open(filename, this.maxNumberOfRatings(1000), this.maxNumberOfRatings(200), separator);

When you reach user number 10000 or item number 200, the following would become test ratings.

Unfortunately, you can only make conditions on the inserted code (int) or on the ratings (Map<code(int),rating(double)>), without coding much.

Greetings.
Jesus Mayor
