### ISSUE TITLE
Cosine Similarity Implementation

### ISSUE THREAD

**Issue by fabioiuri** [ferortega/cf4j#9]
Hey there,

I've been comparing the results I got with the ones cf4j provides, and I've found huge differences on some cases, for example: by using the userToUser knn model on the ML100k dataset, with a 20% test ratio and a k=10, when doing a top-10 evaluation I get a recall value of approximately 0.7, while cf4j obtains a value of approximately 0.23.

Interested in finding out why the difference was so big, I dived into the source code, and I finally found the one bit that is not similar to what I have: the cosine similarity implementation.

For reference, the cosine similarity is computed as follows:
![image](https://user-images.githubusercontent.com/10257696/78586834-f5292100-7833-11ea-9e40-8349a4b7b701.png)

And assuming that R_A denotes the items rated by user A and R_B the items rated by user B, then the cosine similarity is equivalent to:
![image](https://user-images.githubusercontent.com/10257696/78586891-11c55900-7834-11ea-9614-8ba050be920a.png)

And for what I can see in https://github.com/ferortega/cf4j/blob/master/src/cf4j/knn/userToUser/similarities/MetricCosine.java#L19-L33, it seems like what is being computed is:
![image](https://user-images.githubusercontent.com/10257696/78587019-433e2480-7834-11ea-89c5-9c87e14bfb61.png)
because both `denActive` as well as `denTarget` are only incremented when an item in common is found.
This introduces some differences to the similarity outcome, since the denominator factors will not include ratings for items that were interacted by only one of the users, therefore affecting the computation of the k nearest neighbours and providing worse results.

I've locally changed the cosine similarity to represent the original cosine similarity formula, and the obtained results are exactly the ones I had using another framework.

Is this indeed an implementation bug? If so, I would be happy to provide a PR with the required changes.
Or is this some variant I'm not aware of?

Thanks,
Fábio Colaço

**Comment by ferortega** [comment]
Dear @fabioiuri,

Thank you for your comment. I have been checking the formulation of cosine similarity in collaborative filtering environments and the implementation of CF4J is correct.

According to "Adomavicius, G., & Tuzhilin, A. (2005). Toward the next generation of recommender systems: A survey of the state-of-the-art and possible extensions. IEEE transactions on knowledge and data engineering, 17(6), 734-749.", in equation (13) both the numerator and the denominator must be computed using the common ratings between the two users.

Best regards,
Fernando

**Comment by fabioiuri** [comment]
Interesting...
I don't seem to grasp the reason behind this variant proposed for CF environments.

I was using "Empirical Analysis of Predictive Algorithms for Collaborative Filtering, 1998" as reference and they do use the regular cosine in the CF context (eq. 3).

If you do know the improvements generated by applying this variant, please do let me know.
Either way, thanks for the quick clarifications.

Regards,
Fábio Colaço

**Comment by ferortega** [comment]
Probably both approaches are correct. The one which obtains better prediction results will be the best for your dataset. Dealing with the sparsity of the rating matrix is not trivial.
